---
apiVersion: v1
kind: Namespace
metadata:
  name: interview-app

---
# namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-backend-deployment
  namespace: interview-app
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: interview-backend
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: interview-backend
    spec:
      containers:
        - name: interview-backend
          image: interview:backend-1.0
          ports:
            - containerPort: 8081
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  key: mongodb_url
                  name: backend-secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: backend-secrets
---
# for backend service
apiVersion: v1
kind: Service
metadata:
  name: interview-backend-service
  namespace: interview-app
spec:
  type: LoadBalancer
  selector:
    app: interview-backend
  ports:
    - name: http
      protocol: TCP
      port: 5050
      targetPort: 8081
---
# frontend part
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-frontend-deployment
  namespace: interview-app
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: interview-frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: interview-frontend
    spec:
      containers:
        - name: interview-frontend
          image: interview:frontend-1.0
          ports:
            - containerPort: 80
---
# for frontend service
apiVersion: v1
kind: Service
metadata:
  name: interview-frontend-service
  namespace: interview-app
spec:
  type: LoadBalancer
  selector:
    app: interview-frontend
  ports:
    - name: http
      protocol: TCP
      port: 5051
      targetPort: 80
